### ISSUE TITLE
Dependency conflict (path with flutter_test)

### ISSUE THREAD

**Issue by ghost** [Apparence-io/gate#6]
**Describe the bug**
There is a dependency conflict with ```path``` & ```flutter_test``` packages.

```
Because every version of flutter_test from sdk depends on path 1.8.0 and every version of gate_generator from path depends on path ^1.8.1, flutter_test from sdk is incompatible with gate_generator from path.
So, because gate_example depends on both gate_generator from path and flutter_test from sdk, version solving failed.
pub get failed (1; So, because gate_example depends on both gate_generator from path and flutter_test from sdk, version solving failed.)
exit code 1
```

**To Reproduce**
Open the example of gate, run ```flutter pub get```. Error appear.

**Expected behavior**
Pub get work

**Comment by g-apparence** [comment]
check your flutter_test package is up to date, this should work. 
```sdk depends on path 1.8.0 and every version of gate_generator from path depends on path ^1.8.1```

**Comment by ghost** [comment]
Thanks but ```flutter_test``` version is related to the Flutter SDK (now 1.8.0) so we can't modify it:
Dependency override should work but recommended for a package used in Flutter SDK...

```
flutter_test:
    sdk: flutter
```

I suggest to downgrade path to 1.8.0 for now ?

**Comment by g-apparence** [comment]
Yes, 
downgraded : - path and analyzer dependencies
