### ISSUE TITLE
Since Dart 3.0 gate_provider is almost empty + warnings during build

### ISSUE THREAD

**Issue by thomnico** [Apparence-io/gate#9]
**Describe the bug**
Since Dart 3.0 gate_provider is almost empty + warnings during build

It contains only:
// coverage:ignore-file
// ********************************
// Gate generated file
// Do not modify by hand
// ********************************
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target
class AppProvider {
  AppProvider._();

  static final AppProvider instance = AppProvider._();
}

final AppProvider appProvider = AppProvider.instance;

**To Reproduce**
1. upgrade to DartSDK 3.0 and flutter 3.10

2. be sure to rm pubspec.lock etc..
3. Run : dart run build_runner build --delete-conflicting-outputs
4.  you will see msgs like: " [WARNING] source_gen:combining_builder on lib/ui/guards/authenticated_guard.dart:
authenticated_guard.g.dart must be included as a part directive in the input library with:
    part 'authenticated_guard.g.dart';
"
**Expected behavior**
a functional gate_provider.dart.

**Logs **
Run `flutter analyze` and attach any output of that command below.

Paste the output of running `flutter doctor -v` here.
flutter doctor -v                                   
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-FR)
    • Flutter version 3.10.1 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nicolasthomas/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

**Additional context**

**Comment by thomnico** [comment]
Can reproduce the issue with the example project provided by this package.

**Comment by g-apparence** [comment]
Fixed on version 1.1.0

You're welcome.

**Comment by thomnico** [comment]
Fix confirmed thanks
